apiVersion: v1
kind: Template
labels:
  template: jslave-cloudci-stage-builder
metadata:
  annotations:
    description: CloudCI Jenkins Slaves
    iconClass: icon-jenkins
    tags: instant-app,jenkins
  name: jslave-cloudci-stage-builder
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      slave-label: jslave-container-fedora-33-stage
    name: jslave-container-fedora-33-stage
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: jslave-container-fedora-33-stage
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: jslave-container-fedora-33-stage:latest
    resources: {}
    source:
      contextDir: ${CONTEXTDIR}
      git:
        ref: ${REPO_REF}
        uri: ${REPO_URL}
      type: Git
    strategy:
      dockerStrategy:
        forcePull: true
        noCache: true
        env:
          - name: GIT_SSL_NO_VERIFY
            value: 'true'
      type: Docker
    triggers:
    - type: ConfigChange
parameters:
- description: Git repository with Dockerfile and slave entrypoint.
  displayName: Repository URL
  name: REPO_URL
  value: https://github.com/virt-s1/jenkins-cloudci.git
- description: The sub-directory inside the repository.
  displayName: Context Directory
  name: CONTEXTDIR
  value: jslave-stage
- description: The git ref or tag to use for customization.
  displayName: Git Reference
  name: REPO_REF
  value: master
